/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F274_6371();
extern void F276_6533();
extern void F274_6375();
extern void F277_6537();
extern void F279_6701();
extern void F277_6542();
extern void F399_4218();
extern void F321_6217();
extern void F144_1910();
extern EIF_REFERENCE F144_1897();
extern EIF_BOOLEAN F144_1909();
extern EIF_BOOLEAN F144_1917();
extern void F144_1919();
extern void F144_1920();
extern void F144_1921();
extern void F85_1568();
extern EIF_TYPED_VALUE F85_1569();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F274_6371;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F274_6375;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F277_6537;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F277_6542;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F399_4218;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F276_6533;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F279_6701;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F321_6217;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F144_1910;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F144_1909;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F144_1897;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F144_1917;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F144_1919;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F144_1920;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F144_1921;

	egc_str_dtype = 275;

	egc_immstr8_dtype = 274;

	egc_str32_dtype = 278;

	egc_immstr32_dtype = 277;
	egc_arr_dtype = 398;
	egc_tup_dtype = 227;
	egc_disp_rout_id = 2539;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x015A;
	egc_sp_wchar = 0x020E;
	egc_sp_bool = 0x012E;
	egc_sp_uint8 = 0x022C;
	egc_sp_uint16 = 0x02B0;
	egc_sp_uint32 = 0x0287;
	egc_sp_uint64 = 0x01E8;
	egc_sp_int8 = 0x0355;
	egc_sp_int16 = 0x0331;
	egc_sp_int32 = 0x01D5;
	egc_sp_int64 = 0x0379;
	egc_sp_real32 = 0x02E9;
	egc_sp_real64 = 0x030D;
	egc_sp_pointer = 0x0272;
	egc_sp_ref = 0x0191;

	egc_uint8_dtype = 250;
	egc_uint16_dtype = 247;
	egc_uint32_dtype = 244;
	egc_uint64_dtype = 241;
	egc_int8_dtype = 238;
	egc_int16_dtype = 235;
	egc_int32_dtype = 232;
	egc_int64_dtype = 229;
	egc_bool_dtype = 265;
	egc_real32_dtype = 253;
	egc_char_dtype = 262;
	egc_wchar_dtype = 259;
	egc_real64_dtype = 256;
	egc_point_dtype = 268;

	egc_exception_dtype = 103;
	egc_except_emnger_dtype = 143;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_i18n";
	egc_system_location = "D:\\prod\\simple_i18n\\EIFGENs\\simple_i18n_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765238402;
	egc_has_old_special_semantic = 0;
	scount = 1003;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "I18N_TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1307;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 3110;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5477;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 84;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F85_1568;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F85_1569;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 64; /* I18N_TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 198; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 298; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
